version: '3.7'

services:
  api:
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8080:${PORT}

volumes:
  pgadmin_pv: null
